# get the UV layer

FROM ghcr.io/astral-sh/uv:python3.13-trixie-slim

RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# create the working dir

WORKDIR /final_app

# get & install requirements

COPY app/requirements.txt .
RUN uv pip install -r requirements.txt --system

# get the whole app

COPY app/ .

# cfg alembic

RUN mkdir -p /final_app/models/db_schemas/minirag_db/
COPY docker/full_rag_app/alembic.ini /final_app/models/db_schemas/minirag_db/alembic.ini
COPY docker/full_rag_app/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

# run the app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]