"""empty message

Revision ID: 0f0aefed5970
Revises: ee108a4cd5ae
Create Date: 2026-10-02 14:45:22.722636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0aefed5970'
down_revision: Union[str, Sequence[str], None] = 'ee108a4cd5ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('asset_fail_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'asset_fail_error')
    # ### end Alembic commands ###
