"""Add chat & message tables

Revision ID: 1c8e6f45765f
Revises: b314d62cf8cd
Create Date: 2026-09-23 11:36:17.688164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1c8e6f45765f'
down_revision: Union[str, Sequence[str], None] = 'b314d62cf8cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('chat_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_name', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.drop_index(op.f('pgvector_collection_ahmed_384_vector_idx'), table_name='collection_ahmed_384', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('collection_ahmed_384')
    op.drop_index(op.f('pgvector_collection_mohammed_384_vector_idx'), table_name='collection_mohammed_384', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('collection_mohammed_384')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_mohammed_384',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('collection_mohammed_384_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_mohammed_384_pkey'))
    )
    op.create_index(op.f('pgvector_collection_mohammed_384_vector_idx'), 'collection_mohammed_384', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.create_table('collection_ahmed_384',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('collection_ahmed_384_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_ahmed_384_pkey'))
    )
    op.create_index(op.f('pgvector_collection_ahmed_384_vector_idx'), 'collection_ahmed_384', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('messages')
    op.drop_table('chats')
    # ### end Alembic commands ###
