"""empty message

Revision ID: 275ce42a6e01
Revises: d92f4b87c1a0
Create Date: 2026-10-02 14:24:10.807773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '275ce42a6e01'
down_revision: Union[str, Sequence[str], None] = 'd92f4b87c1a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('pgvector_collection_ahmed_384_vector_idx'), table_name='collection_ahmed_384', postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('collection_ahmed_384')
    op.drop_table('collection_b48e293b7d4644f1a4a2fd27a38d4fa1_384')
    op.drop_column('assets', 'asset_status')
    op.drop_constraint(op.f('chats_chat_uuid_key'), 'chats', type_='unique')
    op.drop_column('chats', 'chat_settings')
    op.drop_column('chats', 'chat_uuid')
    op.add_column('runs', sa.Column('duration_s', sa.Float(), nullable=True))
    op.drop_column('runs', 'duration_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('runs', 'duration_s')
    op.add_column('chats', sa.Column('chat_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('chats', sa.Column('chat_settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('chats_chat_uuid_key'), 'chats', ['chat_uuid'], postgresql_nulls_not_distinct=False)
    op.add_column('assets', sa.Column('asset_status', sa.VARCHAR(), server_default=sa.text("'ready'::character varying"), autoincrement=False, nullable=False))
    op.create_table('collection_b48e293b7d4644f1a4a2fd27a38d4fa1_384',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('collection_b48e293b7d4644f1a4a2fd27a38d4fa1_384_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_b48e293b7d4644f1a4a2fd27a38d4fa1_384_pkey'))
    )
    op.create_table('collection_ahmed_384',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('collection_ahmed_384_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_ahmed_384_pkey'))
    )
    op.create_index(op.f('pgvector_collection_ahmed_384_vector_idx'), 'collection_ahmed_384', ['vector'], unique=False, postgresql_ops={'vector': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
