"""empty message

Revision ID: 338e77d0dc15
Revises: 275ce42a6e01
Create Date: 2026-10-02 14:25:34.410494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338e77d0dc15'
down_revision: Union[str, Sequence[str], None] = '275ce42a6e01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_steps', sa.Column('duration_s', sa.Float(), nullable=True))
    op.drop_column('run_steps', 'duration_ms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('run_steps', sa.Column('duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('run_steps', 'duration_s')
    # ### end Alembic commands ###
