"""Init Tables

Revision ID: 6134554d0cc1
Revises: 
Create Date: 2026-09-12 02:08:18.116163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6134554d0cc1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.UUID(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('user_name'),
    sa.UniqueConstraint('user_uuid')
    )
    op.create_table('assets',
    sa.Column('asset_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_uuid', sa.UUID(), nullable=False),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('asset_size', sa.Integer(), nullable=True),
    sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('asset_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('asset_id'),
    sa.UniqueConstraint('asset_user_id', 'asset_name', name='uq_asset_user_name'),
    sa.UniqueConstraint('asset_uuid')
    )
    op.create_index('ix_asset_user_id', 'assets', ['asset_user_id'], unique=False)
    op.create_table('chunks',
    sa.Column('chunk_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chunk_uuid', sa.UUID(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('chunk_name', sa.String(), nullable=False),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_user_id', sa.Integer(), nullable=False),
    sa.Column('chunk_asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_asset_id'], ['assets.asset_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('chunk_user_id', 'chunk_asset_id', 'chunk_name', name='uq_chunk_user_asset_name'),
    sa.UniqueConstraint('chunk_uuid')
    )
    op.create_index('ix_chunk_asset_id', 'chunks', ['chunk_asset_id'], unique=False)
    op.create_index('ix_chunk_user_id', 'chunks', ['chunk_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunk_user_id', table_name='chunks')
    op.drop_index('ix_chunk_asset_id', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_asset_user_id', table_name='assets')
    op.drop_table('assets')
    op.drop_table('users')
    # ### end Alembic commands ###
