"""Simplify Columns

Revision ID: b2cc3699a936
Revises: 1c8e6f45765f
Create Date: 2026-09-23 11:51:44.820478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2cc3699a936'
down_revision: Union[str, Sequence[str], None] = '1c8e6f45765f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('asset_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('assets', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('assets_asset_uuid_key'), 'assets', type_='unique')
    op.drop_constraint(op.f('uq_asset_user_name'), 'assets', type_='unique')
    op.drop_index(op.f('ix_asset_user_id'), table_name='assets')
    op.create_index('ix_asset_user_id', 'assets', ['user_id'], unique=False)
    op.create_unique_constraint('uq_user_asset_name', 'assets', ['user_id', 'asset_name'])
    op.drop_constraint(op.f('assets_asset_user_id_fkey'), 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('assets', 'asset_size')
    op.drop_column('assets', 'asset_uuid')
    op.drop_column('assets', 'asset_user_id')
    op.drop_column('assets', 'asset_config')
    op.add_column('chats', sa.Column('chat_uuid', sa.UUID(), nullable=False))
    op.create_index('ix_chat_user_id', 'chats', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'chats', ['chat_uuid'])
    op.add_column('chunks', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('chunks', sa.Column('asset_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('chunks_chunk_uuid_key'), 'chunks', type_='unique')
    op.drop_constraint(op.f('uq_chunk_user_asset_name'), 'chunks', type_='unique')
    op.drop_index(op.f('ix_chunk_asset_id'), table_name='chunks')
    op.create_index('ix_chunk_asset_id', 'chunks', ['asset_id'], unique=False)
    op.drop_index(op.f('ix_chunk_user_id'), table_name='chunks')
    op.create_index('ix_chunk_user_id', 'chunks', ['user_id'], unique=False)
    op.drop_constraint(op.f('chunks_chunk_asset_id_fkey'), 'chunks', type_='foreignkey')
    op.drop_constraint(op.f('chunks_chunk_user_id_fkey'), 'chunks', type_='foreignkey')
    op.create_foreign_key(None, 'chunks', 'assets', ['asset_id'], ['asset_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'chunks', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('chunks', 'chunk_asset_id')
    op.drop_column('chunks', 'chunk_user_id')
    op.drop_column('chunks', 'chunk_name')
    op.drop_column('chunks', 'chunk_order')
    op.drop_column('chunks', 'chunk_uuid')
    op.create_index('ix_message_chat_id', 'messages', ['chat_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_chat_id', table_name='messages')
    op.add_column('chunks', sa.Column('chunk_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('chunk_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('chunk_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('chunk_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('chunks', sa.Column('chunk_asset_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.create_foreign_key(op.f('chunks_chunk_user_id_fkey'), 'chunks', 'users', ['chunk_user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('chunks_chunk_asset_id_fkey'), 'chunks', 'assets', ['chunk_asset_id'], ['asset_id'], ondelete='CASCADE')
    op.drop_index('ix_chunk_user_id', table_name='chunks')
    op.create_index(op.f('ix_chunk_user_id'), 'chunks', ['chunk_user_id'], unique=False)
    op.drop_index('ix_chunk_asset_id', table_name='chunks')
    op.create_index(op.f('ix_chunk_asset_id'), 'chunks', ['chunk_asset_id'], unique=False)
    op.create_unique_constraint(op.f('uq_chunk_user_asset_name'), 'chunks', ['chunk_user_id', 'chunk_asset_id', 'chunk_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('chunks_chunk_uuid_key'), 'chunks', ['chunk_uuid'], postgresql_nulls_not_distinct=False)
    op.drop_column('chunks', 'asset_id')
    op.drop_column('chunks', 'user_id')
    op.drop_constraint(None, 'chats', type_='unique')
    op.drop_index('ix_chat_user_id', table_name='chats')
    op.drop_column('chats', 'chat_uuid')
    op.add_column('assets', sa.Column('asset_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('assets', sa.Column('asset_user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('asset_uuid', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('assets', sa.Column('asset_size', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key(op.f('assets_asset_user_id_fkey'), 'assets', 'users', ['asset_user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_constraint('uq_user_asset_name', 'assets', type_='unique')
    op.drop_index('ix_asset_user_id', table_name='assets')
    op.create_index(op.f('ix_asset_user_id'), 'assets', ['asset_user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_asset_user_name'), 'assets', ['asset_user_id', 'asset_name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('assets_asset_uuid_key'), 'assets', ['asset_uuid'], postgresql_nulls_not_distinct=False)
    op.drop_column('assets', 'user_id')
    op.drop_column('assets', 'asset_metadata')
    # ### end Alembic commands ###
