"""Add user account fields

Revision ID: b314d62cf8cd
Revises: 6134554d0cc1
Create Date: 2026-09-16 23:46:03.218361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b314d62cf8cd'
down_revision: Union[str, Sequence[str], None] = '6134554d0cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collection_mohammed_384')
    op.add_column('users', sa.Column('user_email', sa.String(), nullable=False))
    op.add_column('users', sa.Column('user_password_hash', sa.String(), nullable=False))
    op.drop_constraint(op.f('users_user_name_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_user_email'), 'users', ['user_email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_user_email'), table_name='users')
    op.create_unique_constraint(op.f('users_user_name_key'), 'users', ['user_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('users', 'user_password_hash')
    op.drop_column('users', 'user_email')
    op.create_table('collection_mohammed_384',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('chunk_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vector', sa.NullType(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.chunk_id'], name=op.f('collection_mohammed_384_chunk_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('collection_mohammed_384_pkey'))
    )
    # ### end Alembic commands ###
