"""empty message

Revision ID: ee108a4cd5ae
Revises: 338e77d0dc15
Create Date: 2026-10-02 14:43:18.273651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee108a4cd5ae'
down_revision: Union[str, Sequence[str], None] = '338e77d0dc15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('asset_status', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'asset_status')
    # ### end Alembic commands ###
